# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):




    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(634, 480)
        Form.setStyleSheet("\n"
"background-color: rgb(0 ,0 , 0);")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(150, 0, 311, 131))
        self.logo.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\sumit\\Desktop\\jarvis\\logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.mainFrame = QtWidgets.QFrame(Form)
        self.mainFrame.setGeometry(QtCore.QRect(30, 140, 561, 311))
        self.mainFrame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 127);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.username = QtWidgets.QLineEdit(self.mainFrame)
        self.username.setGeometry(QtCore.QRect(170, 50, 191, 41))
        self.username.setStyleSheet("border-color: rgb(0, 0,127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setReadOnly(False)
        self.username.setObjectName("username")
        self.Password = QtWidgets.QLineEdit(self.mainFrame)
        self.Password.setGeometry(QtCore.QRect(170, 110, 191, 41))
        self.Password.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Password.setAlignment(QtCore.Qt.AlignCenter)
        self.Password.setObjectName("Password")
        self.Login = QtWidgets.QPushButton(self.mainFrame)
        self.Login.setGeometry(QtCore.QRect(210, 170, 111, 31))
        self.Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Login.setObjectName("Login")
        self.Retry = QtWidgets.QPushButton(self.mainFrame)
        self.Retry.setGeometry(QtCore.QRect(20, 240, 111, 31))
        self.Retry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Retry.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Retry.setObjectName("Retry")
        self.Back = QtWidgets.QPushButton(self.mainFrame)
        self.Back.setGeometry(QtCore.QRect(210, 240, 111, 31))
        self.Back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Back.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Back.setObjectName("Back")
        self.Exit = QtWidgets.QPushButton(self.mainFrame)
        self.Exit.setGeometry(QtCore.QRect(410, 240, 111, 31))
        self.Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Exit.setStyleSheet("border-color: rgb(0, 0, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Exit.setObjectName("Exit")
        self.Wrongcred = QtWidgets.QLabel(self.mainFrame)
        self.Wrongcred.setGeometry(QtCore.QRect(130, -30, 261, 271))
        self.Wrongcred.setText("")
        self.Wrongcred.setPixmap(QtGui.QPixmap("C:\\Users\\sumit\\Desktop\\jarvis\\wrongcred.gif"))
        self.Wrongcred.setScaledContents(True)
        self.Wrongcred.setObjectName("Wrongcred")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setText(_translate("Form", "USERNAME"))

        self.Password.setText(_translate("Form", "PASSWORD"))
        self.Login.setText(_translate("Form", "Login"))
        self.Retry.setText(_translate("Form", "Retry"))
        self.Back.setText(_translate("Form", "Back"))
        self.Exit.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
